# Generated by Django 4.1.3 on 2022-12-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogger_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
